### ISSUE TITLE
All the live demos are broken

### ISSUE THREAD

**Issue by triptych** [fenix-hub/godot-engine.supabase-examples#10]
The links to the live demos point to ( for example ) https://nicolosantilio.com/demos/supabase/todo-list/demo which is a 404.

**Comment by fenix-hub** [comment]
Thanks, I rewrote my website and decided to host my demos somewhere else, but forgot to update this README.
https://demo.nicolosantilio.com/slack-gd/app
https://demo.nicolosantilio.com/todo-list/app
