### ISSUE TITLE
Todo list demo fails to connect

### ISSUE THREAD

**Issue by triptych** [fenix-hub/godot-engine.supabase-examples#11]
Hi! 
I tried the web demo (using the test account )  of the todo list and it fails to connect:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
https://[[omitted for security]].supabase.co/auth/v1/token?grant_type=password

![image](https://user-images.githubusercontent.com/8691/158024283-321c50aa-0e73-4404-8ca6-0d4ffea41a3f.png)

I removed the prefix from the url just for security but it was a string of characters...

**Comment by fenix-hub** [comment]
Hi @triptych !
Thanks for testing the web demos.
Supabase stops running projects after 1 week of inactivity for freemium plans, so projects need to be restored sometimes.
Now both demos are up and running :)
