### ISSUE TITLE
Unable to read .env file at path 'res://.env'

### ISSUE THREAD

**Issue by j2l** [fenix-hub/godot-engine.supabase-examples#8]
Hello,
This project is a very good idea! Congrats!

On Ubuntu 21.04, Godot 3.3.4, I can't get the Todo example working though.
Following wiki/Installation-and-Activation, I populated the .env file (and Godot settings, just in case). I copied it at root and within the html folder.
- In the preview, I don't have any error, just no response from the sign-in button.
- In the browser console I get `Unable to read .env file at path 'res://.env'` even before any login submit.
After a login attempt, I have:
```
index.js:354 **ERROR**: Error parsing URL: /auth/v1/token?grant_type=password.
index.js:354    At: scene/main/http_request.cpp:54:_parse_url() - Condition "err != OK" is true. Returned: err
```

Any idea what I missed?
Thanks

**Comment by fenix-hub** [comment]
@j2l Updated both source code of the example and plugin. Make sure to download the plugin again and let me know
